apiVersion: v1
kind: Service
metadata:
  name: service-torre-controle
spec:
  selector:
    app: hangar-aeronave
    version: stable
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
